### ISSUE TITLE
Erro nos Agendamentos na v4.0.2

### ISSUE THREAD

**Issue by neijobson** [cgugovbr/mod-sei-eouv#11]
@danielcoelhocgu 

A atualização para a versão 4.0.2 passou a dar erro nos Agendamentos:
- executarImportacaoManifestacaoEOuv
- executarImportacaoManifestacaoESic

Veja no print mais abaixo que não tinha erro imediatamente antes da atualização.

**Log do Erro sobre o agendamento "executarImportacaoManifestacaoESic":**
```
Usuário: EOUV/ANATEL
Servidor: seihm.anatel.gov.br
Erro: Exception: Erro: Ocorreu algum erro não tratado. HTTP Status: 503 in /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php:114
Stack trace:
#0 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(228): MdCguEouvAgendamentoRN->apiRestRequest('https://treinaf...', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx...', 1)
#1 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(936): MdCguEouvAgendamentoRN->executarServicoConsultaManifestacoes('https://treinaf...', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx...', '21/01/2024 10:3...', '21/01/2024 11:3...', NULL, 4051)
#2 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(664): MdCguEouvAgendamentoRN->executarImportacaoManifestacaoESic(Array)
#3 /opt/appsei/infra/infra_php/formularios/infra_agendamento_tarefa_lista.php(46): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#4 /opt/appsei/infra/infra_php/InfraControlador.php(111): require_once('/opt/appsei/inf...')
#5 /opt/appsei/sei/web/controlador.php(1707): InfraControlador::processar('infra_agendamen...', Object(PaginaSEI), Object(SessaoSEI), Object(BancoSEI), Object(LogSEI), Object(CacheSEI), Object(AuditoriaSEI))
#6 {main}
Detalhes:

Trilha de Processamento:
#0 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(228): MdCguEouvAgendamentoRN->apiRestRequest('https://treinaf...', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx...', 1)
#1 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(936): MdCguEouvAgendamentoRN->executarServicoConsultaManifestacoes('https://treinaf...', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx...', '21/01/2024 10:3...', '21/01/2024 11:3...', NULL, 4051)
#2 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(664): MdCguEouvAgendamentoRN->executarImportacaoManifestacaoESic(Array)
#3 /opt/appsei/infra/infra_php/formularios/infra_agendamento_tarefa_lista.php(46): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#4 /opt/appsei/infra/infra_php/InfraControlador.php(111): require_once('/opt/appsei/inf...')
#5 /opt/appsei/sei/web/controlador.php(1707): InfraControlador::processar('infra_agendamen...', Object(PaginaSEI), Object(SessaoSEI), Object(BancoSEI), Object(LogSEI), Object(CacheSEI), Object(AuditoriaSEI))
#6 {main}
Navegador: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
GET:
Array
(
[acao] => infra_agendamento_tarefa_executar
[acao_origem] => infra_agendamento_tarefa_listar
[acao_retorno] => infra_agendamento_tarefa_listar
[id_infra_agendamento_tarefa] => 33
[infra_sistema] => 100000100
[infra_unidade_atual] => 110000837
[infra_hash] => xxxxxxxxxxxxxxxxxxxxxxxxxxxx
)

POST:
Array
(
[hdnInfraTipoPagina] => 1
[txtComandoListar] =>
[txtComplementoListar] =>
[selSinSucessoListar] => null
[selSinAtivoListar] => null
[selStaPeriodicidadeExecucaoListar] => null
[hdnInfraNroItens] => 31
[hdnInfraItemId] =>
[hdnInfraItens] => 34,5,3,23,2,7,4,1,6,32,33,14,26,20,10,25,11,18,30,31,8,9,15,17,29,27,28,19,16,21,22
[hdnInfraItensHash] => xxxxxxxxxxxxxxxxxxxxxxxxxxxx
[hdnInfraItensSelecionados] =>
[hdnInfraSelecoes] => Infra
[hdnInfraCampoOrd] => Comando
[hdnInfraTipoOrd] => ASC
)
```

**Log do Erro sobre o agendamento "executarImportacaoManifestacaoEOuv":**

```
Usuário: EOUV/ANATEL
Servidor: seihm.anatel.gov.br
Erro: Exception: Erro: Ocorreu algum erro não tratado. HTTP Status: 503 in /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php:114
Stack trace:
#0 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(228): MdCguEouvAgendamentoRN->apiRestRequest('https://treinaf...', 'xxxxxxxxxxxx...', 1)
#1 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(631): MdCguEouvAgendamentoRN->executarServicoConsultaManifestacoes('https://treinaf...', 'xxxxxxxxxxxx...', '21/01/2024 10:3...', '21/01/2024 11:3...', NULL, 4050)
#2 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(664): MdCguEouvAgendamentoRN->executarImportacaoManifestacaoEOuv(Array)
#3 /opt/appsei/infra/infra_php/formularios/infra_agendamento_tarefa_lista.php(46): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#4 /opt/appsei/infra/infra_php/InfraControlador.php(111): require_once('/opt/appsei/inf...')
#5 /opt/appsei/sei/web/controlador.php(1707): InfraControlador::processar('infra_agendamen...', Object(PaginaSEI), Object(SessaoSEI), Object(BancoSEI), Object(LogSEI), Object(CacheSEI), Object(AuditoriaSEI))
#6 {main}
Detalhes:

Trilha de Processamento:
#0 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(228): MdCguEouvAgendamentoRN->apiRestRequest('https://treinaf...', 'xxxxxxxxxxxx...', 1)
#1 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(631): MdCguEouvAgendamentoRN->executarServicoConsultaManifestacoes('https://treinaf...', 'xxxxxxxxxxxx...', '21/01/2024 10:3...', '21/01/2024 11:3...', NULL, 4050)
#2 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(664): MdCguEouvAgendamentoRN->executarImportacaoManifestacaoEOuv(Array)
#3 /opt/appsei/infra/infra_php/formularios/infra_agendamento_tarefa_lista.php(46): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#4 /opt/appsei/infra/infra_php/InfraControlador.php(111): require_once('/opt/appsei/inf...')
#5 /opt/appsei/sei/web/controlador.php(1707): InfraControlador::processar('infra_agendamen...', Object(PaginaSEI), Object(SessaoSEI), Object(BancoSEI), Object(LogSEI), Object(CacheSEI), Object(AuditoriaSEI))
#6 {main}
Navegador: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
GET:
Array
(
[acao] => infra_agendamento_tarefa_executar
[acao_origem] => infra_agendamento_tarefa_listar
[acao_retorno] => infra_agendamento_tarefa_listar
[id_infra_agendamento_tarefa] => 32
[infra_sistema] => 100000100
[infra_unidade_atual] => 110000837
[infra_hash] => xxxxxxxxxxxxxxxxx
)

POST:
Array
(
[hdnInfraTipoPagina] => 1
[txtComandoListar] =>
[txtComplementoListar] =>
[selSinSucessoListar] => null
[selSinAtivoListar] => null
[selStaPeriodicidadeExecucaoListar] => null
[hdnInfraNroItens] => 31
[hdnInfraItemId] =>
[hdnInfraItens] => 34,5,3,23,2,7,4,1,6,32,33,14,26,20,10,25,11,18,30,31,8,9,15,17,29,27,28,19,16,21,22
[hdnInfraItensHash] => xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[hdnInfraItensSelecionados] =>
[hdnInfraSelecoes] => Infra
[hdnInfraCampoOrd] => Comando
[hdnInfraTipoOrd] => ASC
)
```

**Print que mostra que não tinha erro imediatamente antes da atualização:**

![image](https://github.com/cgugovbr/mod-sei-eouv/assets/49068090/9d780ff3-674b-4fb0-828e-b2b0d9f3c3b8)

**Comment by danielcoelhocgu** [comment]
Olá @neijobson. O erro continua acontecendo constantemente? Esse erro simplesmente indica que ao se conectar ao FalaBR o servidor retornou erro 503, ou seja, estava indisponível.

Nessa última atualização eu coloquei o agendamento para falhar caso não consiga se conectar ao FalaBR. Antes ele continuava normalmente e registrava como importação bem sucedida, o que podia acabar resultando em perda de algumas manifestações na próxima execução do agendamento.

**Comment by danielcoelhocgu** [comment]
Verifiquei no nosso ambiente de testes e esses erros também aconteceram desde sexta-feira. Provavelmente estavam mexendo em alguma coisa no FalaBR treinamento e ficou fora do ar no fim de semana. Normalizou hoje pela manhã.

![image](https://github.com/cgugovbr/mod-sei-eouv/assets/110624029/5ac5085d-3c95-46e3-b111-d058c41bdf3b)

**Comment by neijobson** [comment]
@danielcoelhocgu 
Foi apenas com a nova versão.
Voltei a versão 4.0.1 e imediatamente parou de ocorrer.
Ou seja, com v4.0.2 tem o erro e com v4.0.1 não tem o erro. É imediato!

Preciso de correção para atualizar a versão.

**Comment by danielcoelhocgu** [comment]
Acho que você não entendeu. O erro no agendamento é o comportamento esperado, pois o FalaBR Treinamento estava fora do ar no fim de semana.

Se possível, peço que volte para a versão 4.0.2 e você verá que o erro não acontece mais, pois o sistema está no ar novamente.

O agendamento busca as manifestações cadastradas desde o último agendamento com sucesso. Por isso é importante que o agendamento falhe quando o módulo não conseguir ler os dados do FalaBR.

**Comment by neijobson** [comment]
@danielcoelhocgu 
Você tem razão!

Subi novamente aqui em HM e funcionou liso.
Então já homologuei que Erro no Agendamento não está mais silencioso
Contudo, sugiro implementar também o disparo de e-mail para o e-mail cadastrado no Agendamento para avisar sobre Falha.

Nos testes que fiz aqui as Falhas não enviou e-mail de alerta.

Tão quanto o PHP do Agendamento no core do SEI fica na pasta "rn", é boa prática que nos módulos fique também dentro da pasta "rn" do módulo.
* Vide exemplo do Peticionamento: https://github.com/anatelgovbr/mod-sei-peticionamento/blob/master/sei/web/modulos/peticionamento/rn/MdPetAgendamentoAutomaticoRN.php

**Comment by danielcoelhocgu** [comment]
Implementado no branch *dev*.
